# Site settings
title: "Depo Stok Kayıt - Takip Otomasyonu"
description: >-
  Sistem Analizi ve Tasarımı dersi proje ilerleme günlüğü. 
  Ali Aslan tarafından geliştirilmektedir.
baseurl: "/proje-repo"
url: "https://aliaslaan.github.io"
author: Ali Aslan

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
